[package]
name = "stm32g4xx-clkcfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-time = "0.12.1"
thiserror = "1.0.30"
